- base/Dockerfile
Upgrade required, since Ruby 2.1.5 had a serious security flaw: https://www.ruby-lang.org/en/news/2015/04/13/ruby-2-1-6-released/
> Upgrade to Ruby 2.1.6 and update Bundler to latest.

- appengine/Dockerfile
Three updates:
* Configured nokogiri >= 1.6 to use system-provided libxml2 and libxslt rather than its own vendored versions. This speeds up nokogiri installs substantially because it doesn't need to compile the vendored C code.
* Install the recently released ruby 2.0.0-p648, 2.1.8, and 2.2.4. Keep 2.2.3 as well for a little while until users get off it.
* Bump bundler to 1.11.2.
This has been tested manually by building docker images based on this base image. We should come up with a continuous integration solution for these dockerfiles, however...
> Nokogiri installation speedup; update ruby and bundler versions

- appengine/Dockerfile
I haven't done a push of the last pull request (ruby 2.2.4 and nokogiri speedups) to gcr.io yet. Wanted to get this change in first due to the release of ruby 2.3.
> Add Ruby 2.3.0 to preinstalls; upgrade Node to 5.4.0

- .travis.yml
- appengine/Dockerfile
- appengine/README.md
Also, some updates to the Dockerfile to reduce its size and the time
needed to build it (in part, to speed up runs of tests).
See also https://github.com/GoogleCloudPlatform/ruby-docker/pull/24
> Provide a config to activate Travis-CI.

- appengine/Rakefile
- appengine/test/minimal_app/Dockerfile
- appengine/test/minimal_app/Gemfile
- appengine/test/minimal_app/Gemfile.lock
- appengine/test/minimal_app/config.ru
- appengine/test/tc_base_image.rb
- appengine/test/tc_sample_apps.rb
- appengine/test/test_helper.rb
Provided two Ruby (minitest) based test files, one that runs checks
directly on the base image, and one that builds and runs a set of apps.
Currently, only one test app is provided: a minimal app using Rack.
Also provide a Rakefile that runs the test suite.
> Provide basic tests for the appengine base image

- appengine/Dockerfile
* Rack respects $RACK_HANDLER when no args are supplied
* Rack will default to thin, then puma, then webrick by default (need to
recommend doing puma first).
> no longer default to webrick

- appengine/Dockerfile
- appengine/files/policy.xml
Add a policy.xml file disabling certain capabilities to close off CVE-2016–3714
> Work around for imagemagick security issue

- obsolete/Dockerfile
- obsolete/README.md
This Dockerfile creates a disabled image, displaying an error on image and container creation that points users to the correct base images to use.
Once it is in place, we will switch the auto-build for the obsolete google/ruby, google/ruby-runtime, and google/ruby-hello images to point to this Dockerfile, disabling those images. We may, at some point later, actually delete the images altogether.
> Provide a Dockerfile for obsolete google/ruby images.

- appengine/Dockerfile
Set these to match the current override values in the gcloud-generated Dockerfile so they can be removed from the latter.
> Set application environment variables to production by default

- obsolete/Dockerfile
- obsolete/README.md
This messaging change was previously made in the dockerfile error message, but missed in the README.
> Clarify App Engine usage in the README

- appengine/Dockerfile
- appengine/README.md
- appengine/test/tc_base_image.rb
This should reduce the base image size considerably, but at the cost of eliminating some preinstalled rubies. Therefore, this should not be merged until the gcloud sdk generates Dockerfiles that use the pre-built binary packages to speed up ruby installations (now available in gcloud 126.0.0, released 2016.09.14). Note that we are also changing the default ruby version from 2.3.0 to 2.3.1.
> Configure apt-get to see GCP's pre-built ruby binary packages and preinstall only one ruby using those packages

- appengine/Dockerfile
Testing revealed that if the base image sets RBENV_VERSION, application images downstream could break because RBENV_VERSION overrides other version specifiers. We rename the environment variable to DEFAULT_RUBY_VERSION.
> Don't set RBENV_VERSION in the base image

- .travis.yml
This step used to be in the travis config, IIRC, to force pull the latest base image. However, we're doing that now with `docker build --pull`, so it's redundant. It's also now pulling the incorrect base image since we recently changed to debian8.
> Stop pre-pulling the wrong docker base image in travis tests

- appengine/test/test_base_image.json
The cloud build tests are failing because of this extra trailing comma in config json file.
Test by running `$ appengine/build.sh gcr.io/google_appengine/ruby:test`, and make sure the script at least completes Step 1 without the JSON parsing error.
> Fix trailing comma in test_base_image.json

- appengine/Dockerfile
Add the RUNTIME_DISTRIBUTION argument to Dockerfile, so we have an option to choose which ruby runtime binary distribution repository to use. This also gives us a way to test any staging runtime binaries in GAE Flex workflow.
> Add RUNTIME_DISTRIBUTION argument to Dockerfile

- appengine/Dockerfile
This will cause logs to appear in the Google Cloud console (albeit without severity information, etc.) even if the logging or appengine gems are not installed.
> Cause Rails 5 to log to STDOUT in production by default.

- appengine/Dockerfile
Apparently `paperclip` needs it to check the filetype.
Footprint is 2 extra packages: `file` and `libmagic1` for some reason so should be reasonable.
I've built the image ok, but please, test :)
> Update Dockerfile to include `file` utility

- appengine/test/test_base_image.json
License tests are automated tests to check that all packages installed in the image conform to Google's open source licensing stardards. Check out https://github.com/GoogleCloudPlatform/runtimes-common/blob/master/structure_tests/licenses_test.go (and the corresponding README) for more details.
> adding license tests to ruby structure tests

- builder/.gitignore
- builder/Rakefile
- builder/build.sh
- builder/build_build_app.sh
- builder/build_gen_dockerfile.sh
- builder/build_pipeline.sh
- builder/build_steps/build_app.yaml.in
- builder/build_steps/build_app/Dockerfile.in
- builder/build_steps/gen_dockerfile.yaml.in
- builder/build_steps/gen_dockerfile/Dockerfile.in
- builder/build_steps/gen_dockerfile/build_script.rb
- builder/build_steps/gen_dockerfile/templates/Dockerfile.erb
- builder/build_steps/shared/build_info.rb
- builder/ruby.yaml.in
- builder/test/tc_sample_apps.rb
- test/test_helper.rb
The theme here is to implement versioning support for ruby build steps. This capability ties together a specific version of the base image and specific versions of the build steps by referencing their tags explicitly in the build pipeline config.
Specific changes:
* The entrypoint for the `gen_dockerfile` build step now understands the `--base-image-tag` flag. This lets the pipeline specify the specific base image version to use for an app.
* The scripts for building the build steps now take parameters for the build step version `TAG`, the `PROJECT` name, and the `BASE_TAG` for the base image the step itself is based on. To support this, we had to preprocess the steps' Dockerfiles so `BASE_TAG` is injected into the `FROM` instruction (which otherwise cannot be parameterized).
* There is …
> Update ruby build steps to support runtime build versions

- appengine/image_files/Dockerfile
NodeJS 6.9.5 is the latest LTS.
Bundler 1.14.3 is the latest. There were some rapid-fire bug fixes to the 1.14 series in late January but it seems to have stabilized now.
> Update nodejs and bundler to the latest versions

- appengine/README.md
- appengine/image_files/Dockerfile
Remove the ENTRYPOINT from the base image.
This was a vestige of the pre-beta design where we were using ENTRYPOINT rather than CMD. Currently, the image generated by App Engine Flex during deployment must clear the ENTRYPOINT and set CMD instead. We'd like to clean this up so that images based on this base image don't have to clear the ENTRYPOINT. We also want to match other language base images, which all either use CMD or don't set a default at all.
This is a potential breaking change if any users have a custom image based on the ruby base image that depend on the default ENTRYPOINT setting. I don't expect this would happen commonly if ever, since the Dockerfile generated by `app gen-config --custom` clears the ENTRYPOINT itself. (It would not affect `runtime: ruby` customers at all.) …
> Clear base image entrypoint

- appengine/image_files/Dockerfile
- appengine/test/tc_ruby_versions.rb
Added libicu-dev, libgit2-dev, and cmake to the list of packages installed. This will let App Engine Flex applications install the charlock_holmes and rugged gems (which are in the top 1k based on installs) without needing to break glass with a custom Dockerfile.
Also did a bit of minor cleanup in the dockerfile, and added Ruby 2.4.0 to the list of rubies to test.
> Add a few more libraries for common gems

- README.md
- appengine/README.md
- appengine/Rakefile
- appengine/image_files/Dockerfile
- builder/build_steps/build_app/Dockerfile.in
- builder/build_steps/gen_dockerfile/Dockerfile.in
- builder/build_steps/gen_dockerfile/templates/Dockerfile.erb
- builder/test/tc_sample_apps.rb
- obsolete/Dockerfile
- obsolete/README.md
These forms are equivalent, but GCR team recommends the hyphens over underscores for consistency.
> Change GCR project name to the canonical hyphenated form

- builder/build_pipeline.sh
- builder/build_steps/gen_dockerfile/build_script.rb
- builder/ruby.yaml.in
Includes the following:
* Generates versioned runtime pipeline definitions.
* Move app build tasks (such as asset precompilation) before Dockerfile generation in the build pipeline.
* Debian packages now specified by a toplevel "packages" field in app.yaml rather than a subfield of "runtime_config"
> Update build pipeline to match latest versions and packages proposals

- appengine/test/tc_ruby_versions.rb
I just built 2.4.1 and pushed to packages.cloud.google.com.
> Add Ruby 2.4.1 to test suite

- builder/build_steps/gen_dockerfile/build_script.rb
- builder/build_steps/gen_dockerfile/templates/Dockerfile.erb
- builder/test/sample_apps/rack_app/app.yaml
- builder/test/sample_apps/rails4_app/app.yaml
- builder/test/tc_sample_apps.rb
Improvements for entrypoint handling in the runtime builder (does not affect pre-builder behavior). Currently, gen-dockerfile indiscriminately prepends "exec" to an entrypoint, in an attempt to forward signals properly to the process running in the container. This fails in a variety of cases, including:
* the entrypoint already begins with "exec"
* the entrypoint begins with a shell builtin such as "cd"
* the entrypoint runs several binaries separated by `;`, `&&`, `||`, or `|`.
This updates the logic to avoid prepending "exec" in cases when it is likely to fail. We still do prepend it by default because that is the current behavior of the pre-builder external runtimes system, and because it is the right thing to do in the common case.
We also now support array (i.e. Dockerfile "exec" …
> Allow array entrypoints, and suppress exec if not safe

- builder/build_pipeline.sh
- builder/build_steps/build_app/build_script.rb
Workaround for internal issue b/33233310. Currently the Cloud Build environment provides the correct metadata service (yielding the correct credentials) when accessed by hostname (metadata.google.internal) but not by IP address. The cloud_sql_proxy gets its default credentials from metadata by IP address, which is why it won't start in a build step. Until that is resolved, we explicitly get the current oauth token from the metadata service (by hostname), and pass it explicitly to cloud_sql_proxy.
Note even with this workaround, cloud_sql_proxy is still failing in this environment because of a separate issue (b/33415496). But at least this removes one of the two dependencies.
> Manual auth of cloud_sql_proxy to work around issues getting metadata by IP address

- builder/build_steps/shared/run_build_step.sh
Don't depend on the path `/workspace`. Instead, pass the actual working directory into the build scripts.
> Path to the builder working directory can be other than /workspace

- appengine/build.sh
- builder/build_pipeline.sh
- builder/build_step.sh
The gcloud container commands used during builds are now released and no longer require the beta tag.
> Use released versions instead of beta versions of gcloud container commands

- builder/build_steps/build_app/build_script.rb
- builder/build_steps/shared/build_info.rb
The `env_variables` provided by app.yaml need to be honored during build steps.
Also, `cloud_sql_proxy` doesn't seem to respond to SIGINT—it hangs the build—so just kill it instead.
> Ensure requested env variables are set during builds

- builder/build_pipeline.sh
- builder/build_step.sh
- builder/build_steps/build_app/build_script.rb
- builder/build_steps/shared/build_info.rb
- builder/runtimes.yaml.in
Previously the build-app step always attempted to start cloud_sql_proxy, and exposed all databases in the project. Now we only expose the database(s) explicitly called out in the app.yaml config, and if there are none, we don't even start cloud_sql_proxy at all.
Also modified the script that builds test pipelines so it updates the new manifest file.
> Builder starts cloud_sql_proxy only for explicitly requested instances

- test/sample_apps/deploy_check/Gemfile
- test/sample_apps/deploy_check/Gemfile.lock
- test/sample_apps/deploy_check/app.rb
- test/sample_apps/deploy_check/app.yaml
- test/sample_apps/deploy_check/spec/hello_world_spec.rb
This is taken from https://github.com/GoogleCloudPlatform/ruby-docs-samples, and is used to ensure basic flex deploys work as intended.
@dazuma @hxiong388
> Add hello world application for deploy check test

- appengine/image_files/.gemrc
- appengine/image_files/Dockerfile
- appengine/test/ruby_versions/Dockerfile
- builder/generate_dockerfile/files/Dockerfile.erb
Simplify gem install scripts by providing default flags in a global .gemrc in the base image.
> Add global .gemrc to base image

- builder/build_pipeline.sh
- builder/build_tools/files/access_cloud_sql
- builder/generate_dockerfile/files/Dockerfile.erb
- builder/generate_dockerfile/files/app_config.rb
- builder/generate_dockerfile/files/generate_dockerfile.rb
- builder/ruby-latest.yaml
- builder/ruby.yaml.in
Prior to July 24, the docker containers that ran runtime build steps didn't provide full access to the correct metadata service (and thus credentials) due to internal issues b/33233310 and b/63630627. As a result, when a build step required the cloud_sql_proxy, we had to employ a workaround that obtained an access token separately and jumped through some hoops to pass it to the cloud_sql_proxy.
Now that b/33233310 and b/63630627 are fixed, all build step containers are connected to a network that includes the correct metadata service. The workaround is no longer necessary---and indeed now seems to be breaking things in a few cases. So this PR removes it.
This PR also includes the following related fixes:
* Fixed builder/build_pipeline.sh which was referencing old script names.
* Modified …
> Remove obsolete auth workarounds for build environment

- builder/generate_dockerfile/files/Dockerfile.erb
- builder/generate_dockerfile/files/generate_dockerfile.rb
- builder/test/test_generate_dockerfile.rb
Combine environment variables in the generated Dockerfile to reduce the number of layers in case the application has a lot of environment variables.
> Combine env instructions in generated Dockerfile

- appengine/image_files/Dockerfile
- appengine/test/tc_ruby_versions.rb
- builder/build_tools/Dockerfile.in
* Add newly released Ruby versions 2.2.8, 2.3.5, and 2.4.2 to the test suite.
* Set default Ruby version to 2.3.5. Usually I'd like to wait a week for any issues to shake out, but in this case there were some critical security fixes.
* Update NodeJS to the latest LTS (6.11.3), and bundler to the latest stable (1.15.4)
> Support newly released Ruby versions

- ruby-generate-dockerfile/app/Dockerfile.erb
- ruby-generate-dockerfile/app/app_config.rb
- test/tc_generate_dockerfile.rb
Previously the Dockerfile generation for the Ruby runtime always prefaced build steps with `/build_tools/access_cloud_sql` (which starts the cloud_sql_proxy) if there is a CloudSQL instance present in the configuration. This bit of "magic" usually does the right thing, or at least doesn't do any (significant) harm. But it is often unnecessary, and having this extra magic has been making me uncomfortable. It is also inconsistent with how other runtimes that allow configuring of build steps work (e.g. node and elixir).
Changing this so that `/build_tools/access_cloud_sql` must be explicit in the build step (as configured in app.yaml) if it is desired. We adjust the code that computes the default build step (for Rails apps) so it includes `/build_tools/access_cloud_sql` in the computed …
> Make access_cloud_sql explicit in build steps

- ruby-build-tools/access_cloud_sql
- ruby-generate-dockerfile/app/Dockerfile.erb
- ruby-generate-dockerfile/app/app_config.rb
- test/tc_generate_dockerfile.rb
Currently if the sqladmin api is not enabled or the cloudbuild service account doesn't have permissions, then access_cloud_sql will fail with an error in the default rails build step, which means assets won't get precompiled. Most asset precompilation won't actually need to hit the database, and we'd like the default generated build step to work in as many cases as possible, so we'll have it use the lenient behavior where it will continue even if it can't establish the database connection.
> Make access_cloud_sql lenient in the default asset precompile step

- ruby-build-tools/Dockerfile
- ruby-generate-dockerfile/app/Dockerfile.erb
- ruby-generate-dockerfile/app/app_config.rb
- test/tc_app_config.rb
- test/tc_build_tools.rb
Installs the gcloud SDK in the builder image so that build commands can run gcloud, gsutil, and other useful SDK commands during the build phase. Also fixes the project ID determination, which is needed to set the default gcloud project config.
> Provide gcloud to build commands

- ruby-build-tools/Dockerfile
- ruby-build-tools/access_cloud_sql
* Update gcloud to version 180.0.1
* access_cloud_sql no longer depends on the /build_tools path.
> Updates to build tools

- ruby-generate-dockerfile/app/app_config.rb
- test/tc_app_config.rb
- test/tc_generate_dockerfile.rb
Support the dotenv_config setting in app.yaml, generating a build step that builds a `.env` file from a runtime config resource.
> Support dotenv_config

- ruby-generate-dockerfile/app/app_config.rb
- test/app_config/gemfile-ruby/gems.rb
- test/tc_app_config.rb
If there isn't a `.ruby-version` file, attempt to get the ruby version from the Gemfile first, before falling back to the default version. This should, among other things, make it easier to move from Heroku.
> Pick up ruby version from gemfile

- ruby-base/README.md
Also fix broken link to bookshelf tutorial.
> Replace "Container Engine" by "Kubernetes Engine".

- ruby-base/Dockerfile
Using jemalloc can reduce Ruby memory usage by 30%.
It makes sense to include this in the base image.
Ref: https://medium.com/@adrienjarthon/ruby-jemalloc-results-for-updown-io-d3fb2d32f67f
> Add libjemalloc-dev to ruby-base

- ruby-pipeline/ruby-latest.yaml
A Kaniko 0.8 bug is affecting the runtime (see https://github.com/GoogleCloudPlatform/ruby-docker/issues/165). Switch back to Docker until https://github.com/GoogleContainerTools/kaniko/pull/546 is included in a Kaniko release.
/cc @dlorenc
> Switch back to docker until Kaniko PR 546 is released

- ruby-base/README.md
Try to remove the invalid example, as people may hit on `no bundle` error with this example.
Ref. https://github.com/GoogleCloudPlatform/ruby-docker/issues/161
> Remove the invalid example from README.md

- app-engine-exec-wrapper/README.md
- app-engine-exec-wrapper/execute.sh
exec-wrapper can be used for data migrations for Cloud Run applications, as seen in the [Django on Cloud Run tutorial](https://cloud.google.com/python/django/run).
However, for Cloud Run applications whose images are built with [Cloud Buildpacks](https://github.com/GoogleCloudPlatform/buildpack), the Docker command in `execute.sh` needs to specify an entrypoint so that a custom command can be run (as Buildpacks define the entrypoint as the web process defined in `Procfile`, and this needs to be overridden)
This PR adds this functionality, as well as some additions to the exec-wrapper readme to show it's usage.
> feat: add `--entrypoint` to support buildpack-based images

- runtime-config.env
- tools/ci-scripts/deploy_check.sh
- tools/ci-scripts/integration-test.sh
Kokoro Builds:
- deploy_check
- integration-test
- integration-test-builder
> fix(ruby-docker): add pip install trusted hosts to fix SSLCertVerificationError
